version: "3.5"

services:
  web:
    image: webdevops/php-nginx:7.3
    working_dir: /app
    ports:
      - 80:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mysql:5.6
    volumes:
      - ./docker/dbcreation.sql:/tmp/dbcreation.sql
      - ./docker/import.sh:/tmp/import.sh
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: symfonydemo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ipssi 
      MYSQL_PASSWORD: ipssi

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "20000:80"
    environment:  
      PMA_HOST: database